export default function () {
  return {
    queryString: '',
    sesameStatus: null,
    sesameMessage: '',
    activityStream: [],
    tableStatus: null,
    tableMessage: '',
    tableData: [],
    tablePagination: {
      sortBy: 'id',
      descending: false,
      page: 1,
      rowsPerPage: 30,
      rowsNumber: 0,
    },
    cutoutSize: 200,
    cutoutFOV: 60,
    cutoutExpandAll: false,
    schema: null,
    tableList: [],
    tableColumnsObject: [],
    tableColumnsDescription: {},
    tableColumnsTicked: [
      'lotss.id',
      'lotss.source_id',
      'lotss.ra',
      // 'lotss.e_ra',
      'lotss.dec',
      // 'lotss.e_dec',
      'lotss.sp',
      // 'lotss.e_sp',
      'lotss.si',
      // 'lotss.e_si',
      'lotss.maj',
      // 'lotss.e_maj',
      'lotss.min',
      // 'lotss.e_min',
      // 'lotss.dc_maj',
      // 'lotss.e_dc_maj',
      // 'lotss.dc_min',
      // 'lotss.e_dc_min',
      'lotss.pa',
      // 'lotss.e_pa',
      // 'lotss.dc_pa',
      // 'lotss.e_dc_pa',
      'lotss.rms',
      'lotss.type',
      'lotss.mosaic',
      'lotss.n_point',
      'lotss.masked_fraction',
      'p3d.plateifu',
      'p3d.mangaid',
      'p3d.log_mass',
      'p3d.g_r',
    ],
  }
}
