from django.db import models


class Lotss(models.Model):
    """

    Shimwell et al. (2022) A&A 659, A1
    """
    id = models.BigIntegerField(primary_key=True, help_text="ID column")
    source_id = models.CharField(
        max_length=22, blank=True, null=True, help_text="Original source identifier")
    ra = models.FloatField(blank=True, null=True,
                           help_text="J2000 right ascension")
    e_ra = models.FloatField(blank=True, null=True, help_text="RA error")
    dec = models.FloatField(blank=True, null=True,
                            help_text="J2000 declination")
    e_dec = models.FloatField(blank=True, null=True, help_text="DEC error")
    sp = models.FloatField(blank=True, null=True,
                           help_text="Peak brightness [mJy/beam]")
    e_sp = models.FloatField(blank=True, null=True, help_text="Error")
    si = models.FloatField(blank=True, null=True,
                           help_text="Integrated flux density [mJy]")
    e_si = models.FloatField(blank=True, null=True, help_text="Error")
    maj = models.FloatField(blank=True, null=True, help_text="Major axis")
    e_maj = models.FloatField(blank=True, null=True, help_text="Erorr")
    min = models.FloatField(blank=True, null=True, help_text="Minor xis")
    e_min = models.FloatField(blank=True, null=True, help_text="Erorr")
    dc_maj = models.FloatField(
        blank=True, null=True, help_text="Deconvolved major axis")
    e_dc_maj = models.FloatField(blank=True, null=True, help_text="Erorr")
    dc_min = models.FloatField(
        blank=True, null=True, help_text="Deconvolved minor axis")
    e_dc_min = models.FloatField(blank=True, null=True, help_text="Erorr")
    pa = models.FloatField(blank=True, null=True, help_text="Positional angle")
    e_pa = models.FloatField(blank=True, null=True, help_text="Error")
    dc_pa = models.FloatField(blank=True, null=True,
                              help_text="Deconvolved positional angle")
    e_dc_pa = models.FloatField(blank=True, null=True, help_text="Error")
    rms = models.FloatField(
        blank=True, null=True, help_text="Local noise at the source location (RMS)")
    type = models.CharField(max_length=1, blank=True, null=True, help_text="Type of source as classified by PyBDSF. "
                            "Type – here `S` indicates an isolated source fit with a single Gaussian; "
                            "`C` represents sources fit by a single Gaussian but within an island of emission that contains other sources; "
                            "and ‘M’ is used for sources that are extended and fitted with multiple Gaussians.")
    mosaic = models.CharField(
        max_length=32, blank=True, null=True, help_text="The mosaic identifier")
    n_point = models.FloatField(
        blank=True, null=True, help_text="Number of pointings that are mosaiced at the position of the source")
    masked_fraction = models.FloatField(
        blank=True, null=True, help_text="Primary beam attenuation weighted average of the deconvolution mask images at the source location")
    p3d = models.ForeignKey('P3D', models.DO_NOTHING, related_name='lotss', related_query_name='lotss',
                            db_column='p3d', blank=True, null=True, help_text="MaNGA PLATE-IFU ID and the main ID for Pipe3D data")

    class Meta:
        managed = False
        db_table = 'lotss'


class P3D(models.Model):
    """
    MaNGA Pipe3D value added catalog
    S.F.Sanchez and the IA-MaNGA team
    https://www.sdss.org/dr17/manga/manga-data/manga-pipe3d-value-added-catalog/
    """
    mangaid = models.CharField(
        max_length=11, blank=True, null=True, help_text="MaNGA ID")
    plate = models.IntegerField(
        blank=True, null=True, help_text="plate ID of the MaNGA cube")
    ifudsgn = models.IntegerField(
        blank=True, null=True, help_text="IFU bundle ID of the MaNGA cube")
    plateifu = models.CharField(
        primary_key=True, max_length=11, help_text="code formed by the plate and ifu names")
    objra = models.FloatField(blank=True, null=True,
                              help_text="RA of the object")
    objdec = models.FloatField(
        blank=True, null=True, help_text="DEC of the object")
    name = models.CharField(max_length=17, blank=True, null=True)
    log_sfr_ha = models.FloatField(blank=True, null=True)
    fov = models.FloatField(blank=True, null=True)
    re_kpc = models.FloatField(blank=True, null=True)
    e_log_mass = models.FloatField(blank=True, null=True)
    e_log_sfr_ha = models.FloatField(blank=True, null=True)
    log_mass = models.FloatField(
        blank=True, null=True, help_text="Integrated stellar mass in units of the solar mass in log scale [log(Msun)]")
    log_sfr_ssp = models.FloatField(blank=True, null=True)
    log_nii_ha_cen = models.FloatField(blank=True, null=True)
    e_log_nii_ha_cen = models.FloatField(blank=True, null=True)
    log_oiii_hb_cen = models.FloatField(blank=True, null=True)
    e_log_oiii_hb_cen = models.FloatField(blank=True, null=True)
    log_sii_ha_cen = models.FloatField(blank=True, null=True)
    e_log_sii_ha_cen = models.FloatField(blank=True, null=True)
    log_oii_hb_cen = models.FloatField(blank=True, null=True)
    e_log_oii_hb_cen = models.FloatField(blank=True, null=True)
    ew_ha_cen = models.FloatField(blank=True, null=True)
    e_ew_ha_cen = models.FloatField(blank=True, null=True)
    zh_lw_re_fit = models.FloatField(blank=True, null=True)
    e_zh_lw_re_fit = models.FloatField(blank=True, null=True)
    alpha_zh_lw_re_fit = models.FloatField(blank=True, null=True)
    e_alpha_zh_lw_re_fit = models.FloatField(blank=True, null=True)
    zh_mw_re_fit = models.FloatField(blank=True, null=True)
    e_zh_mw_re_fit = models.FloatField(blank=True, null=True)
    alpha_zh_mw_re_fit = models.FloatField(blank=True, null=True)
    e_alpha_zh_mw_re_fit = models.FloatField(blank=True, null=True)
    age_lw_re_fit = models.FloatField(blank=True, null=True)
    e_age_lw_re_fit = models.FloatField(blank=True, null=True)
    alpha_age_lw_re_fit = models.FloatField(blank=True, null=True)
    e_alpha_age_lw_re_fit = models.FloatField(blank=True, null=True)
    age_mw_re_fit = models.FloatField(blank=True, null=True)
    e_age_mw_re_fit = models.FloatField(blank=True, null=True)
    alpha_age_mw_re_fit = models.FloatField(blank=True, null=True)
    e_alpha_age_mw_re_fit = models.FloatField(blank=True, null=True)
    re_arc = models.FloatField(blank=True, null=True)
    dl = models.FloatField(blank=True, null=True)
    da = models.FloatField(blank=True, null=True)
    pa = models.FloatField(blank=True, null=True)
    ellip = models.FloatField(blank=True, null=True)
    log_mass_gas = models.FloatField(blank=True, null=True)
    vel_sigma_re = models.FloatField(blank=True, null=True)
    e_vel_sigma_re = models.FloatField(blank=True, null=True)
    log_sfr_sf = models.FloatField(blank=True, null=True)
    log_sfr_d_c = models.FloatField(blank=True, null=True)
    oh_o3n2_cen = models.FloatField(blank=True, null=True)
    e_oh_o3n2_cen = models.FloatField(blank=True, null=True)
    oh_n2_cen = models.FloatField(blank=True, null=True)
    e_oh_n2_cen = models.FloatField(blank=True, null=True)
    oh_ons_cen = models.FloatField(blank=True, null=True)
    e_oh_ons_cen = models.FloatField(blank=True, null=True)
    oh_r23_cen = models.FloatField(blank=True, null=True)
    e_oh_r23_cen = models.FloatField(blank=True, null=True)
    oh_pyqz_cen = models.FloatField(blank=True, null=True)
    e_oh_pyqz_cen = models.FloatField(blank=True, null=True)
    oh_t2_cen = models.FloatField(blank=True, null=True)
    e_oh_t2_cen = models.FloatField(blank=True, null=True)
    oh_m08_cen = models.FloatField(blank=True, null=True)
    e_oh_m08_cen = models.FloatField(blank=True, null=True)
    oh_t04_cen = models.FloatField(blank=True, null=True)
    e_oh_t04_cen = models.FloatField(blank=True, null=True)
    oh_dop_cen = models.FloatField(blank=True, null=True)
    e_oh_dop_cen = models.FloatField(blank=True, null=True)
    oh_o3n2_epm09_cen = models.FloatField(blank=True, null=True)
    e_oh_o3n2_epm09_cen = models.FloatField(blank=True, null=True)
    log_oi_ha_cen = models.FloatField(blank=True, null=True)
    e_log_oi_ha_cen = models.FloatField(blank=True, null=True)
    ha_hb_cen = models.FloatField(blank=True, null=True)
    e_ha_hb_cen = models.FloatField(blank=True, null=True)
    log_nii_ha_re = models.FloatField(blank=True, null=True)
    e_log_nii_ha_re = models.FloatField(blank=True, null=True)
    log_oiii_hb_re = models.FloatField(blank=True, null=True)
    e_log_oiii_hb_re = models.FloatField(blank=True, null=True)
    log_sii_ha_re = models.FloatField(blank=True, null=True)
    e_log_sii_ha_re = models.FloatField(blank=True, null=True)
    log_oii_hb_re = models.FloatField(blank=True, null=True)
    e_log_oii_hb_re = models.FloatField(blank=True, null=True)
    log_oi_ha_re = models.FloatField(blank=True, null=True)
    e_log_oi_ha_re = models.FloatField(blank=True, null=True)
    ew_ha_re = models.FloatField(blank=True, null=True)
    e_ew_ha_re = models.FloatField(blank=True, null=True)
    ha_hb_re = models.FloatField(blank=True, null=True)
    e_ha_hb_re = models.FloatField(blank=True, null=True)
    log_nii_ha_all = models.FloatField(blank=True, null=True)
    e_log_nii_ha_all = models.FloatField(blank=True, null=True)
    log_oiii_hb_all = models.FloatField(blank=True, null=True)
    e_log_oiii_hb_all = models.FloatField(blank=True, null=True)
    log_sii_ha_all = models.FloatField(blank=True, null=True)
    e_log_sii_ha_all = models.FloatField(blank=True, null=True)
    log_oii_hb_all = models.FloatField(blank=True, null=True)
    e_log_oii_hb_all = models.FloatField(blank=True, null=True)
    log_oi_ha_all = models.FloatField(blank=True, null=True)
    e_log_oi_ha_all = models.FloatField(blank=True, null=True)
    ew_ha_all = models.FloatField(blank=True, null=True)
    e_ew_ha_all = models.FloatField(blank=True, null=True)
    ha_hb_all = models.FloatField(blank=True, null=True)
    sigma_mass_cen = models.FloatField(blank=True, null=True)
    e_sigma_mass_cen = models.FloatField(blank=True, null=True)
    sigma_mass_re = models.FloatField(blank=True, null=True)
    e_sigma_mass_re = models.FloatField(blank=True, null=True)
    sigma_mass_all = models.FloatField(blank=True, null=True)
    e_sigma_mass_all = models.FloatField(blank=True, null=True)
    t30 = models.FloatField(blank=True, null=True)
    zh_t30 = models.FloatField(blank=True, null=True)
    zh_re_t30 = models.FloatField(blank=True, null=True)
    a_zh_t30 = models.FloatField(blank=True, null=True)
    t40 = models.FloatField(blank=True, null=True)
    zh_t40 = models.FloatField(blank=True, null=True)
    zh_re_t40 = models.FloatField(blank=True, null=True)
    a_zh_t40 = models.FloatField(blank=True, null=True)
    t50 = models.FloatField(blank=True, null=True)
    zh_t50 = models.FloatField(blank=True, null=True)
    zh_re_t50 = models.FloatField(blank=True, null=True)
    a_zh_t50 = models.FloatField(blank=True, null=True)
    t60 = models.FloatField(blank=True, null=True)
    zh_t60 = models.FloatField(blank=True, null=True)
    zh_re_t60 = models.FloatField(blank=True, null=True)
    a_zh_t60 = models.FloatField(blank=True, null=True)
    t70 = models.FloatField(blank=True, null=True)
    zh_t70 = models.FloatField(blank=True, null=True)
    zh_re_t70 = models.FloatField(blank=True, null=True)
    a_zh_t70 = models.FloatField(blank=True, null=True)
    t80 = models.FloatField(blank=True, null=True)
    zh_t80 = models.FloatField(blank=True, null=True)
    zh_re_t80 = models.FloatField(blank=True, null=True)
    a_zh_t80 = models.FloatField(blank=True, null=True)
    t90 = models.FloatField(blank=True, null=True)
    zh_t90 = models.FloatField(blank=True, null=True)
    zh_re_t90 = models.FloatField(blank=True, null=True)
    a_zh_t90 = models.FloatField(blank=True, null=True)
    t95 = models.FloatField(blank=True, null=True)
    zh_t95 = models.FloatField(blank=True, null=True)
    zh_re_t95 = models.FloatField(blank=True, null=True)
    a_zh_t95 = models.FloatField(blank=True, null=True)
    t99 = models.FloatField(blank=True, null=True)
    zh_t99 = models.FloatField(blank=True, null=True)
    zh_re_t99 = models.FloatField(blank=True, null=True)
    a_zh_t99 = models.FloatField(blank=True, null=True)
    log_mass_gas_av_gas_oh = models.FloatField(blank=True, null=True)
    log_mass_gas_av_ssp_oh = models.FloatField(blank=True, null=True)
    vel_ssp_2 = models.FloatField(blank=True, null=True)
    e_vel_ssp_2 = models.FloatField(blank=True, null=True)
    vel_ha_2 = models.FloatField(blank=True, null=True)
    e_vel_ha_2 = models.FloatField(blank=True, null=True)
    vel_ssp_1 = models.FloatField(blank=True, null=True)
    e_vel_ssp_1 = models.FloatField(blank=True, null=True)
    vel_ha_1 = models.FloatField(blank=True, null=True)
    e_vel_ha_1 = models.FloatField(blank=True, null=True)
    log_sfr_ssp_100myr = models.FloatField(blank=True, null=True)
    log_sfr_ssp_10myr = models.FloatField(blank=True, null=True)
    vel_disp_ha_cen = models.FloatField(blank=True, null=True)
    vel_disp_ssp_cen = models.FloatField(blank=True, null=True)
    vel_disp_ha_1re = models.FloatField(blank=True, null=True)
    vel_disp_ssp_1re = models.FloatField(blank=True, null=True)
    log_mass_in_re = models.FloatField(blank=True, null=True)
    ml_int = models.FloatField(blank=True, null=True)
    ml_avg = models.FloatField(blank=True, null=True)
    f_ha_cen = models.FloatField(blank=True, null=True)
    e_f_ha_cen = models.FloatField(blank=True, null=True)
    r50_kpc_v = models.FloatField(blank=True, null=True)
    e_r50_kpc_v = models.FloatField(blank=True, null=True)
    r50_kpc_mass = models.FloatField(blank=True, null=True)
    e_r50_kpc_mass = models.FloatField(blank=True, null=True)
    log_mass_corr_in_r50_v = models.FloatField(blank=True, null=True)
    e_log_mass_corr_in_r50_v = models.FloatField(blank=True, null=True)
    log_mass_gas_av_gas_log_log = models.FloatField(blank=True, null=True)
    av_gas_re = models.FloatField(blank=True, null=True)
    e_av_gas_re = models.FloatField(blank=True, null=True)
    av_ssp_re = models.FloatField(blank=True, null=True)
    e_av_ssp_re = models.FloatField(blank=True, null=True)
    lambda_re = models.FloatField(blank=True, null=True)
    e_lambda_re = models.FloatField(blank=True, null=True)
    nsa_redshift = models.FloatField(blank=True, null=True)
    nsa_mstar = models.FloatField(blank=True, null=True)
    nsa_inclination = models.FloatField(blank=True, null=True)
    flux_oii3726_03_re_fit = models.FloatField(blank=True, null=True)
    e_flux_oii3726_03_re_fit = models.FloatField(blank=True, null=True)
    flux_oii3726_03_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_oii3726_03_alpha_fit = models.FloatField(blank=True, null=True)
    flux_oii3728_82_re_fit = models.FloatField(blank=True, null=True)
    e_flux_oii3728_82_re_fit = models.FloatField(blank=True, null=True)
    flux_oii3728_82_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_oii3728_82_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hi3734_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3734_re_fit = models.FloatField(blank=True, null=True)
    flux_hi3734_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3734_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hi3798_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3798_re_fit = models.FloatField(blank=True, null=True)
    flux_hi3798_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3798_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hei3889_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hei3889_re_fit = models.FloatField(blank=True, null=True)
    flux_hei3889_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hei3889_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hi3889_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3889_re_fit = models.FloatField(blank=True, null=True)
    flux_hi3889_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hi3889_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hei3965_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hei3965_re_fit = models.FloatField(blank=True, null=True)
    flux_hei3965_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hei3965_alpha_fit = models.FloatField(blank=True, null=True)
    flux_neiii_3967_re_fit = models.FloatField(blank=True, null=True)
    e_flux_neiii_3967_re_fit = models.FloatField(blank=True, null=True)
    flux_neiii_3967_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_neiii_3967_alpha_fit = models.FloatField(blank=True, null=True)
    flux_caii3968_re_fit = models.FloatField(blank=True, null=True)
    e_flux_caii3968_re_fit = models.FloatField(blank=True, null=True)
    flux_caii3968_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_caii3968_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hepsilon3970_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hepsilon3970_re_fit = models.FloatField(blank=True, null=True)
    flux_hepsilon3970_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hepsilon3970_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hdelta4102_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hdelta4102_re_fit = models.FloatField(blank=True, null=True)
    flux_hdelta4102_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hdelta4102_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hgamma4340_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hgamma4340_re_fit = models.FloatField(blank=True, null=True)
    flux_hgamma4340_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hgamma4340_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hbeta4861_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hbeta4861_re_fit = models.FloatField(blank=True, null=True)
    flux_hbeta4861_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hbeta4861_alpha_fit = models.FloatField(blank=True, null=True)
    flux_oiii_4959_re_fit = models.FloatField(blank=True, null=True)
    e_flux_oiii_4959_re_fit = models.FloatField(blank=True, null=True)
    flux_oiii_4959_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_oiii_4959_alpha_fit = models.FloatField(blank=True, null=True)
    flux_oiii_5007_re_fit = models.FloatField(blank=True, null=True)
    e_flux_oiii_5007_re_fit = models.FloatField(blank=True, null=True)
    flux_oiii_5007_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_oiii_5007_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hei5016_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hei5016_re_fit = models.FloatField(blank=True, null=True)
    flux_hei5016_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hei5016_alpha_fit = models.FloatField(blank=True, null=True)
    flux_ni5198_re_fit = models.FloatField(blank=True, null=True)
    e_flux_ni5198_re_fit = models.FloatField(blank=True, null=True)
    flux_ni5198_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_ni5198_alpha_fit = models.FloatField(blank=True, null=True)
    flux_ni5200_re_fit = models.FloatField(blank=True, null=True)
    e_flux_ni5200_re_fit = models.FloatField(blank=True, null=True)
    flux_ni5200_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_ni5200_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hei5876_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hei5876_re_fit = models.FloatField(blank=True, null=True)
    flux_hei5876_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hei5876_alpha_fit = models.FloatField(blank=True, null=True)
    flux_nai5890_re_fit = models.FloatField(blank=True, null=True)
    e_flux_nai5890_re_fit = models.FloatField(blank=True, null=True)
    flux_nai5890_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_nai5890_alpha_fit = models.FloatField(blank=True, null=True)
    flux_nai5896_re_fit = models.FloatField(blank=True, null=True)
    e_flux_nai5896_re_fit = models.FloatField(blank=True, null=True)
    flux_nai5896_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_nai5896_alpha_fit = models.FloatField(blank=True, null=True)
    flux_oi6300_re_fit = models.FloatField(blank=True, null=True)
    e_flux_oi6300_re_fit = models.FloatField(blank=True, null=True)
    flux_oi6300_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_oi6300_alpha_fit = models.FloatField(blank=True, null=True)
    flux_nii6548_re_fit = models.FloatField(blank=True, null=True)
    e_flux_nii6548_re_fit = models.FloatField(blank=True, null=True)
    flux_nii6548_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_nii6548_alpha_fit = models.FloatField(blank=True, null=True)
    flux_halpha6563_re_fit = models.FloatField(blank=True, null=True)
    e_flux_halpha6563_re_fit = models.FloatField(blank=True, null=True)
    flux_halpha6563_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_halpha6563_alpha_fit = models.FloatField(blank=True, null=True)
    flux_nii6583_re_fit = models.FloatField(blank=True, null=True)
    e_flux_nii6583_re_fit = models.FloatField(blank=True, null=True)
    flux_nii6583_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_nii6583_alpha_fit = models.FloatField(blank=True, null=True)
    flux_sii6716_re_fit = models.FloatField(blank=True, null=True)
    e_flux_sii6716_re_fit = models.FloatField(blank=True, null=True)
    flux_sii6716_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_sii6716_alpha_fit = models.FloatField(blank=True, null=True)
    flux_sii6731_re_fit = models.FloatField(blank=True, null=True)
    e_flux_sii6731_re_fit = models.FloatField(blank=True, null=True)
    flux_sii6731_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_sii6731_alpha_fit = models.FloatField(blank=True, null=True)
    flux_ariii7136_re_fit = models.FloatField(blank=True, null=True)
    e_flux_ariii7136_re_fit = models.FloatField(blank=True, null=True)
    flux_ariii7136_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_ariii7136_alpha_fit = models.FloatField(blank=True, null=True)
    flux_hi9015_re_fit = models.FloatField(blank=True, null=True)
    e_flux_hi9015_re_fit = models.FloatField(blank=True, null=True)
    flux_hi9015_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_hi9015_alpha_fit = models.FloatField(blank=True, null=True)
    flux_siii9069_re_fit = models.FloatField(blank=True, null=True)
    e_flux_siii9069_re_fit = models.FloatField(blank=True, null=True)
    flux_siii9069_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_siii9069_alpha_fit = models.FloatField(blank=True, null=True)
    flux_feii9471_re_fit = models.FloatField(blank=True, null=True)
    e_flux_feii9471_re_fit = models.FloatField(blank=True, null=True)
    flux_feii9471_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_feii9471_alpha_fit = models.FloatField(blank=True, null=True)
    flux_siii9531_re_fit = models.FloatField(blank=True, null=True)
    e_flux_siii9531_re_fit = models.FloatField(blank=True, null=True)
    flux_siii9531_alpha_fit = models.FloatField(blank=True, null=True)
    e_flux_siii9531_alpha_fit = models.FloatField(blank=True, null=True)
    oh_mar13_n2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_mar13_n2_re_fit = models.FloatField(blank=True, null=True)
    oh_mar13_n2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_mar13_n2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_mar13_o3n2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_mar13_o3n2_re_fit = models.FloatField(blank=True, null=True)
    oh_mar13_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_mar13_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_t04_re_fit = models.FloatField(blank=True, null=True)
    e_oh_t04_re_fit = models.FloatField(blank=True, null=True)
    oh_t04_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_t04_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pet04_n2_lin_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_n2_lin_re_fit = models.FloatField(blank=True, null=True)
    oh_pet04_n2_lin_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_n2_lin_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pet04_n2_poly_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_n2_poly_re_fit = models.FloatField(blank=True, null=True)
    oh_pet04_n2_poly_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_n2_poly_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pet04_o3n2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_o3n2_re_fit = models.FloatField(blank=True, null=True)
    oh_pet04_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pet04_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_kew02_n2o2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_kew02_n2o2_re_fit = models.FloatField(blank=True, null=True)
    oh_kew02_n2o2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_kew02_n2o2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pil10_ons_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pil10_ons_re_fit = models.FloatField(blank=True, null=True)
    oh_pil10_ons_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pil10_ons_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pil10_on_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pil10_on_re_fit = models.FloatField(blank=True, null=True)
    oh_pil10_on_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pil10_on_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pil11_ns_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pil11_ns_re_fit = models.FloatField(blank=True, null=True)
    oh_pil11_ns_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pil11_ns_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_rs32_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_rs32_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_rs32_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_rs32_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r3_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r3_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r3_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r3_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3o2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3o2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3o2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3o2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_s2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_s2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_s2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_s2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_n2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_n2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_n2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_n2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r23_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r23_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_r23_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_r23_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3n2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3n2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3n2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3s2_re_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3s2_re_fit = models.FloatField(blank=True, null=True)
    oh_cur20_o3s2_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_cur20_o3s2_alpha_fit = models.FloatField(blank=True, null=True)
    oh_kk04_re_fit = models.FloatField(blank=True, null=True)
    e_oh_kk04_re_fit = models.FloatField(blank=True, null=True)
    oh_kk04_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_kk04_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    oh_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    oh_pil16_s_re_fit = models.FloatField(blank=True, null=True)
    e_oh_pil16_s_re_fit = models.FloatField(blank=True, null=True)
    oh_pil16_s_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_pil16_s_alpha_fit = models.FloatField(blank=True, null=True)
    oh_ho_re_fit = models.FloatField(blank=True, null=True)
    e_oh_ho_re_fit = models.FloatField(blank=True, null=True)
    oh_ho_alpha_fit = models.FloatField(blank=True, null=True)
    e_oh_ho_alpha_fit = models.FloatField(blank=True, null=True)
    u_dors_o32_re_fit = models.FloatField(blank=True, null=True)
    e_u_dors_o32_re_fit = models.FloatField(blank=True, null=True)
    u_dors_o32_alpha_fit = models.FloatField(blank=True, null=True)
    e_u_dors_o32_alpha_fit = models.FloatField(blank=True, null=True)
    u_dors_s_re_fit = models.FloatField(blank=True, null=True)
    e_u_dors_s_re_fit = models.FloatField(blank=True, null=True)
    u_dors_s_alpha_fit = models.FloatField(blank=True, null=True)
    e_u_dors_s_alpha_fit = models.FloatField(blank=True, null=True)
    u_mor16_o23_fs_re_fit = models.FloatField(blank=True, null=True)
    e_u_mor16_o23_fs_re_fit = models.FloatField(blank=True, null=True)
    u_mor16_o23_fs_alpha_fit = models.FloatField(blank=True, null=True)
    e_u_mor16_o23_fs_alpha_fit = models.FloatField(blank=True, null=True)
    u_mor16_o23_ts_re_fit = models.FloatField(blank=True, null=True)
    e_u_mor16_o23_ts_re_fit = models.FloatField(blank=True, null=True)
    u_mor16_o23_ts_alpha_fit = models.FloatField(blank=True, null=True)
    e_u_mor16_o23_ts_alpha_fit = models.FloatField(blank=True, null=True)
    nh_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    e_nh_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    nh_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    e_nh_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    no_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_r_re_fit = models.FloatField(blank=True, null=True)
    no_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_r_alpha_fit = models.FloatField(blank=True, null=True)
    no_pil16_ho_r_re_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_ho_r_re_fit = models.FloatField(blank=True, null=True)
    no_pil16_ho_r_alpha_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_ho_r_alpha_fit = models.FloatField(blank=True, null=True)
    no_pil16_n2_r2_re_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_n2_r2_re_fit = models.FloatField(blank=True, null=True)
    no_pil16_n2_r2_alpha_fit = models.FloatField(blank=True, null=True)
    e_no_pil16_n2_r2_alpha_fit = models.FloatField(blank=True, null=True)
    ne_oster_s_re_fit = models.FloatField(blank=True, null=True)
    e_ne_oster_s_re_fit = models.FloatField(blank=True, null=True)
    ne_oster_s_alpha_fit = models.FloatField(blank=True, null=True)
    e_ne_oster_s_alpha_fit = models.FloatField(blank=True, null=True)
    hd_re_fit = models.FloatField(blank=True, null=True)
    e_hd_re_fit = models.FloatField(blank=True, null=True)
    hd_alpha_fit = models.FloatField(blank=True, null=True)
    e_hd_alpha_fit = models.FloatField(blank=True, null=True)
    hb_re_fit = models.FloatField(blank=True, null=True)
    e_hb_re_fit = models.FloatField(blank=True, null=True)
    hb_alpha_fit = models.FloatField(blank=True, null=True)
    e_hb_alpha_fit = models.FloatField(blank=True, null=True)
    mgb_re_fit = models.FloatField(blank=True, null=True)
    e_mgb_re_fit = models.FloatField(blank=True, null=True)
    mgb_alpha_fit = models.FloatField(blank=True, null=True)
    e_mgb_alpha_fit = models.FloatField(blank=True, null=True)
    fe5270_re_fit = models.FloatField(blank=True, null=True)
    e_fe5270_re_fit = models.FloatField(blank=True, null=True)
    fe5270_alpha_fit = models.FloatField(blank=True, null=True)
    e_fe5270_alpha_fit = models.FloatField(blank=True, null=True)
    fe5335_re_fit = models.FloatField(blank=True, null=True)
    e_fe5335_re_fit = models.FloatField(blank=True, null=True)
    fe5335_alpha_fit = models.FloatField(blank=True, null=True)
    e_fe5335_alpha_fit = models.FloatField(blank=True, null=True)
    d4000_re_fit1 = models.FloatField(blank=True, null=True)
    e_d4000_re_fit = models.FloatField(blank=True, null=True)
    d4000_alpha_fit = models.FloatField(blank=True, null=True)
    e_d4000_alpha_fit = models.FloatField(blank=True, null=True)
    hdmod_re_fit = models.FloatField(blank=True, null=True)
    e_hdmod_re_fit = models.FloatField(blank=True, null=True)
    hdmod_alpha_fit = models.FloatField(blank=True, null=True)
    e_hdmod_alpha_fit = models.FloatField(blank=True, null=True)
    hg_re_fit = models.FloatField(blank=True, null=True)
    e_hg_re_fit = models.FloatField(blank=True, null=True)
    hg_alpha_fit = models.FloatField(blank=True, null=True)
    e_hg_alpha_fit = models.FloatField(blank=True, null=True)
    u_band_mag = models.FloatField(blank=True, null=True)
    u_band_mag_error = models.FloatField(blank=True, null=True)
    u_band_abs_mag = models.FloatField(blank=True, null=True)
    u_band_abs_mag_error = models.FloatField(blank=True, null=True)
    g_band_mag = models.FloatField(blank=True, null=True)
    g_band_mag_error = models.FloatField(blank=True, null=True)
    g_band_abs_mag = models.FloatField(blank=True, null=True)
    g_band_abs_mag_error = models.FloatField(blank=True, null=True)
    r_band_mag = models.FloatField(blank=True, null=True)
    r_band_mag_error = models.FloatField(blank=True, null=True)
    r_band_abs_mag = models.FloatField(blank=True, null=True)
    r_band_abs_mag_error = models.FloatField(blank=True, null=True)
    i_band_mag = models.FloatField(blank=True, null=True)
    i_band_mag_error = models.FloatField(blank=True, null=True)
    i_band_abs_mag = models.FloatField(blank=True, null=True)
    i_band_abs_mag_error = models.FloatField(blank=True, null=True)
    b_band_mag = models.FloatField(blank=True, null=True)
    b_band_mag_error = models.FloatField(blank=True, null=True)
    b_band_abs_mag = models.FloatField(blank=True, null=True)
    b_band_abs_mag_error = models.FloatField(blank=True, null=True)
    v_band_mag = models.FloatField(blank=True, null=True)
    v_band_mag_error = models.FloatField(blank=True, null=True)
    v_band_abs_mag = models.FloatField(blank=True, null=True)
    v_band_abs_mag_error = models.FloatField(blank=True, null=True)
    rj_band_mag = models.FloatField(blank=True, null=True)
    rj_band_mag_error = models.FloatField(blank=True, null=True)
    rj_band_abs_mag = models.FloatField(blank=True, null=True)
    rj_band_abs_mag_error = models.FloatField(blank=True, null=True)
    r50 = models.FloatField(blank=True, null=True)
    error_r50 = models.FloatField(blank=True, null=True)
    r90 = models.FloatField(blank=True, null=True)
    error_r90 = models.FloatField(blank=True, null=True)
    c = models.FloatField(blank=True, null=True)
    e_c = models.FloatField(blank=True, null=True)
    b_v = models.FloatField(blank=True, null=True)
    error_b_v = models.FloatField(blank=True, null=True)
    b_r = models.FloatField(blank=True, null=True)
    error_b_r = models.FloatField(blank=True, null=True)
    log_mass_phot = models.FloatField(blank=True, null=True)
    e_log_mass_phot = models.FloatField(blank=True, null=True)
    v_band_sb_at_re = models.FloatField(blank=True, null=True)
    error_v_band_sb_at_re = models.FloatField(blank=True, null=True)
    v_band_sb_at_r_50 = models.FloatField(blank=True, null=True)
    error_v_band_sb_at_r_50 = models.FloatField(blank=True, null=True)
    nsa_sersic_n_morph = models.FloatField(blank=True, null=True)
    u_g = models.FloatField(blank=True, null=True)
    g_r = models.FloatField(blank=True, null=True, help_text="g-r NSA color")
    r_i = models.FloatField(blank=True, null=True)
    i_z = models.FloatField(blank=True, null=True)
    p_cd = models.FloatField(blank=True, null=True)
    p_e = models.FloatField(blank=True, null=True)
    p_s0 = models.FloatField(blank=True, null=True)
    p_sa = models.FloatField(blank=True, null=True)
    p_sab = models.FloatField(blank=True, null=True)
    p_sb = models.FloatField(blank=True, null=True)
    p_sbc = models.FloatField(blank=True, null=True)
    p_sc = models.FloatField(blank=True, null=True)
    p_scd = models.FloatField(blank=True, null=True)
    p_sd = models.FloatField(blank=True, null=True)
    p_sdm = models.FloatField(blank=True, null=True)
    p_sm = models.FloatField(blank=True, null=True)
    p_irr = models.FloatField(blank=True, null=True)
    best_type_n = models.IntegerField(blank=True, null=True)
    best_type = models.CharField(max_length=32, blank=True, null=True)
    nsa_nsaid = models.BigIntegerField(blank=True, null=True)
    vmax_w = models.FloatField(blank=True, null=True)
    num_w = models.FloatField(blank=True, null=True)
    qcflag = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'p3d'
